version: '3.7'
services:
  confluence:
    image: atlassian/confluence-server:latest
    container_name: confluence
    hostname: confluence
    restart: unless-stopped
    volumes:
      - ../Data/confluence:/var/atlassian/application-data/confluence
    environment:
      - TZ=America/Chicago
      - ATL_PROXY_NAME=confluence.homelab.hackingserver.com
      - ATL_PROXY_PORT=443
      - ATL_TOMCAT_PORT=8090
      - ATL_TOMCAT_SCHEME=https
      - ATL_TOMCAT_SECURE=true
    labels:
      - "server"

  confluence-postgresql:
    image: postgres:latest
    container_name: confluence_db
    hostname: confluence_db
    restart: unless-stopped
    volumes:
      - ../Data/postgres:/var/lib/postgresql/data
    environment:
      - TZ=America/Chicago
      - POSTGRES_USER=confluencedb
      # CHANGE THE PASSWORD!
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_DB=confluencedb
      - POSTGRES_ENCODING=UTF8
      - POSTGRES_COLLATE=C
      - POSTGRES_COLLATE_TYPE=C
    labels:
      - "database"

  confluence-nginx:
    image: nginx
    container_name: confluence_proxy
    hostname: confluence_proxy
    depends_on:
      - confluence
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../config/nginx.conf:/etc/nginx/nginx.conf
      - ../config/private:/etc/ssl/private
    environment:
      - TZ=America/Chicago
    labels:
      - "proxy"
