version: '3.7'
services:
  confluence:
    image: atlassian/confluence-server:latest
    container_name: confluence
    hostname: confluence
    restart: unless-stopped
    volumes:
      - ../Data/confluence:/var/atlassian/application-data/confluence
    environment:
      - TZ=America/Chicago
      - ATL_PROXY_NAME=confluence.example.com # TODO: CHANGEME
      - ATL_PROXY_PORT=443
      - ATL_TOMCAT_PORT=8090
      - ATL_TOMCAT_SCHEME=https
      - ATL_TOMCAT_SECURE=true
    labels:
      # Traefik Labels
      - "traefik.enable=true"
      # HTTPS Labels
      - "traefik.http.routers.confluence.rule=Host(`localhost`)" # Domain Name
      - "traefik.http.routers.confluence.entrypoints=web-secure"
      - "traefik.http.routers.confluence.middlewares=default-headers@file"
      - "traefik.http.routers.confluence.service=confluence"
      - "traefik.http.routers.confluence.tls=true"
      - "traefik.http.services.confluence.loadbalancer.server.port=8090" # Proxied Port

  confluence-postgresql:
    image: postgres:latest
    container_name: confluence_db
    hostname: confluence_db
    restart: unless-stopped
    volumes:
      - ../Data/postgres:/var/lib/postgresql/data
    environment:
      - TZ=America/Chicago
      - POSTGRES_USER=confluencedb
      - POSTGRES_PASSWORD=changeme # TODO: CHANGEME
      - POSTGRES_DB=confluencedb
      - POSTGRES_ENCODING=UTF8
      - POSTGRES_COLLATE=C
      - POSTGRES_COLLATE_TYPE=C
